### ISSUE TITLE
Can not install GenieACS on Ubuntu 64bit (instal succesfull on Ubuntu 32bit)

### ISSUE THREAD

**Issue by LeVanVuong93** [genieacs/genieacs#321]
Hi,
Now, I can install GenieACS on Ubuntu 32bit, but not install on Ubuntu 64bit.
I checked the log file and found that there is a difference when executing the command "sudo npm install libxmljs" and "sudo npm install -g genieacs" as shown below.
Therefore, the server receives a "command not found" error when executing the command "genieacs-cwmp", "genieacs-nbi" and "genieacs-fs"

Could someone help me ?
Thank a lot!

1. When executing the command "sudo npm install libxmljs" on Ubuntu 32bit

> vuonglv@acs1-cmctelecom-vn:~$ sudo npm install libxmljs
> 
> > libxmljs@0.19.5 install /home/vuonglv/node_modules/libxmljs
> > node-pre-gyp install --fallback-to-build --loglevel http
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download 
> node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-ia32.tar.gz
> node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-ia32.tar.gz
> node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-ia32.tar.gz 
> node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@7.10.1 (node-v51 ABI, glibc) (falling back to source compile with node-gyp) 
> node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-ia32.tar.gz 
> gyp http GET https://nodejs.org/download/release/v7.10.1/node-v7.10.1-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v7.10.1/node-v7.10.1-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v7.10.1/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v7.10.1/SHASUMS256.txt
> make: Entering directory '/home/vuonglv/node_modules/libxmljs/build'
>   CXX(target) Release/obj.target/xmljs/src/libxmljs.o
`.......(continue).........`

2. When executing the command "sudo npm install libxmljs" on Ubuntu 64bit (you can saw that OS 64bit cannot install packets like OS 32bit)
```
vuonglv@acs1-cmctelecom-vn:~$ sudo npm install libxmljs

> libxmljs@0.19.5 install /home/vuonglv/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-x64.tar.gz
node-pre-gyp http 302 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v51-linux-x64.tar.gz
[libxmljs] Success: "/home/vuonglv/node_modules/libxmljs/build/Release/xmljs.node" is installed via remote
/home/vuonglv
```

3. When executing the command "sudo npm install -g genieacs" on Ubuntu 32bit
```
vuonglv@acs1-cmctelecom-vn:~$ sudo npm install -g genieacs
/usr/bin/genieacs-cwmp -> /usr/lib/node_modules/genieacs/bin/genieacs-cwmp
/usr/bin/genieacs-fs -> /usr/lib/node_modules/genieacs/bin/genieacs-fs
/usr/bin/genieacs-nbi -> /usr/lib/node_modules/genieacs/bin/genieacs-nbi

> libxmljs@0.18.8 install /usr/lib/node_modules/genieacs/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-ia32.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-ia32.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.8 and node@7.10.1 (node-v51 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-ia32.tar.gz 
make: Entering directory '/usr/lib/node_modules/genieacs/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
............(continue)............
```

4. When executing the command "sudo npm install -g genieacs" on Ubuntu 64bit (you can saw that OS 64bit cannot install packets like OS 32bit) 

```
vuonglv@acs1-cmctelecom-vn:~$ sudo npm install -g genieacs
/usr/bin/genieacs-cwmp -> /usr/lib/node_modules/genieacs/bin/genieacs-cwmp
/usr/bin/genieacs-fs -> /usr/lib/node_modules/genieacs/bin/genieacs-fs
/usr/bin/genieacs-nbi -> /usr/lib/node_modules/genieacs/bin/genieacs-nbi

> libxmljs@0.18.8 install /usr/lib/node_modules/genieacs/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-x64.tar.gz
node-pre-gyp http 302 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not installable for libxmljs@0.18.8 and node@7.10.1 (node-v51 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error ENOTDIR: Cannot cd into '/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/vuonglv/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/genieacs/node_modules/libxmljs/.node-gyp"
gyp http GET https://nodejs.org/download/release/v7.10.1/node-v7.10.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.10.1/node-v7.10.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.10.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.10.1/SHASUMS256.txt
make: Entering directory '/usr/lib/node_modules/genieacs/node_modules/libxmljs/build'
make: *** No rule to make target '../.node-gyp/7.10.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/genieacs/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-131-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release" "--node_abi_napi=node-v51"
gyp ERR! cwd /usr/lib/node_modules/genieacs/node_modules/libxmljs
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release --node_abi_napi=node-v51' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-131-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /usr/lib/node_modules/genieacs/node_modules/libxmljs
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release --node_abi_napi=node-v51' (1)
/usr/lib
â””â”€â”€ (empty)

npm ERR! Linux 4.4.0-131-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "genieacs"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.8 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vuonglv/.npm/_logs/
```

**Comment by ccelatabenu** [comment]
I am having the same problem, but I cant install on 32 or 64 bit, and this only began occuring in the last month or so.  I was successful before the last ubuntu 16.04 updates.  Is there anyone who knows how to fix this?

**Comment by LeVanVuong93** [comment]
Right now, I still install on Ubuntu 32bit successfully, only fail on Ubuntu 64bit, and maybe this began occuring in the two week ago or so :(

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this
issue and take it to the mailing list.

**Comment by ccelatabenu** [comment]
genieacs fails to install using the posted directions on git for ubuntu 16.04 here:

https://github.com/genieacs/genieacs/wiki/Installation-Guide-Ubuntu-16.04

and, thats not a bug?
interesting.

**Comment by akcoder** [comment]
No, because those are user supplied instructions :). Besides, you will get
a lot more help on the mailing list :).

**Comment by prajyodh** [comment]
Hi
I am facing the same issue while installing on Ubuntu 16.04 64-bit.
Any one aware on how to fix this?
