### ISSUE TITLE
geneos-nbi worker dies with: TypeError: Key must be a buffer at new Hmac (crypto.js:91:16)

### ISSUE THREAD

**Issue by FransM** [genieacs/genieacs#332]
This is in 1.1.3.

CPE sends UDPConnectionRequestAddress to GenieACS
GenieACS does not try to set or fetch the ConnectionRequestPassword.
If there is no password, the signature calculation gives this error
TypeError: Key must be a buffer at new Hmac (crypto.js:91:16)
And in the GUI I get an EOFError.

Issue is in api-functions.js

around line 189 it reads:
    if (device.Device != null) {
      connectionRequestUrl = device.Device.ManagementServer.ConnectionRequestURL._value;
      udpConnectionRequestAddress = (ref = device.Device.ManagementServer) != null ? (ref1 = ref.UDPConnectionRequestAddress) != null ? ref1._value : void 0 : void 0;
      username = (ref2 = device.Device.ManagementServer.ConnectionRequestUsername) != null ? ref2._value : void 0;
      password = (ref3 = device.Device.ManagementServer.ConnectionRequestPassword) != null ? ref3._value : void 0;

This means that if ConnectionRequestPassword does not exist that password will be void 0;
password itself is passed to udpConReq as key. 
In that function (line 60) calculation of HMac is done with this line:

  sig = crypto.createHmac('sha1', key).update("" + ts + id + un + cn).digest('hex');

This is where the fail is.

Possible solutions:
- if ConnectionRequestPassword does not exist use "" instead of void 0;
- don't try to make the connection but e.g. let udpConReq return false if key is not defined
- set a ConnectionRequestPassword whenever a new device is detected

**Comment by p-alik** [comment]
I got the issue also. @FransM are you going to prepare a PR to fix it?
