### ISSUE TITLE
Unexpected reserved word when run the server

### ISSUE THREAD

**Issue by ihabZhaika** [genieacs/genieacs#349]
Hey,
I have followed the wiki to install the master version of the code, after 
doing
```
npm install
npm run build
```

then try to run 

`./dist/bin/genieacs-cwmp
`
i get the following error

```
[user@localhost genieacs]$ ./dist/bin/genieacs-cwmp
/home/user/Downloads/genieacs/dist/bin/genieacs-cwmp:2
"use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}const path=require("path"),fs=require("fs"),os=require("os"),cluster=_interopDefault(require("cluster")),http=require("http"),https=require("https"),zlib=require("zlib"),crypto=require("crypto"),vm=require("vm"),seedrandom=_interopDefault(require("seedrandom")),child_process=require("child_process"),later=require("later"),mongodb=require("mongodb"),parsimmon=require("parsimmon"),util=require("util"),tls=require("tls"),yaml=require("yaml");let configDir,cwmpSsl,nbiSsl,fsSsl,uiSsl,ROOT_DIR=path.resolve(__dirname,"..");for(;!fs.existsSync(`${ROOT_DIR}/package.json`);){const e=path.resolve(ROOT_DIR,"..");if(e===ROOT_DIR){ROOT_DIR=process.cwd();break}ROOT_DIR=e}const options={EXT_DIR:{type:"path",default:path.resolve(ROOT_DIR,"config/ext")},MONGODB_CONNECTION_URL:{type:"string",default:"mongodb://127.0.0.1/genieacs"},CWMP_WORKER_PROCESSES:{type:"int",default:0},C

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
I have tried it on Ubuntu 18.04 and Feadora28
Any suggestion howto solve this issue ?

**Comment by DrumSergio** [comment]
This issue tracker is intended for code bugs, if you're trying to install it, then you can use my own installation method: https://github.com/DrumSergio/GenieACS-Docker

**Comment by ihabZhaika** [comment]
@DrumSergio
I'ts sort of bug, if you can not run the code then the code has issue

**Comment by akcoder** [comment]
If you are trying to run master, then you are on your own right now. The
wiki is for supporting the released versions. So as Sergio said, this is
not an issue for the defect tracker. Please close this issue and ask your
question on the forum (forum.genieacs.com)

**Comment by ihabZhaika** [comment]
ol
